#pragma once


#define RANGE_DELIMITER_SIGN "-"
#define SUBNET_AND_MASK_DELIMITER "/"

#define DEFAULT_SUFFIX "\n"
#define DEFAULT_PREFIX ""

#define RECORD_DECORATOR_MAX_LENGTH 31
#define RECORDS_DELIMITER_MAX_LENGTH 31
#define IP_MAX_LENGTH 39



#define RECORD_DECORATOR_SIZE (RECORD_DECORATOR_MAX_LENGTH + 1)
#define RECORDS_DELIMITER_SIZE (RECORDS_DELIMITER_MAX_LENGTH + 1)

#define IP_RANGE_MAX_LENGTH (2 * IP_MAX_LENGTH + 1)
#define IP_RANGE_SIZE (IP_RANGE_MAX_LENGTH + 1)