//
// Created by mw on 26.07.23.
//

#ifndef PRESENTATION_TEST_SUBNETTRANSFORMERIPV4_HPP
#define PRESENTATION_TEST_SUBNETTRANSFORMERIPV4_HPP


class SubnetTransformerIPv4 {

};


#endif //PRESENTATION_TEST_SUBNETTRANSFORMERIPV4_HPP
