#pragma once


#define RANGE_DELIMITER_SIGN "-"
#define SUBNET_AND_MASK_DELIMITER "/"

#define DEFAULT_SUFFIX "\n"
#define DEFAULT_PREFIX ""


#define RECORD_DECORATOR_MAX_LENGTH 31
#define RECORDS_DELIMITER_MAX_LENGTH 31

#define RECORD_DECORATOR_SIZE (RECORD_DECORATOR_MAX_LENGTH + 1)
#define RECORDS_DELIMITER_SIZE (RECORDS_DELIMITER_MAX_LENGTH + 1)